The gui breaks when a blank optical disc is in the drive as it doesn't have a path:
File "/usr/lib/python3.5/site-packages/shredder/views/locations.py",
line 360, in add_entry
    path = path.strip()
AttributeError: 'NoneType' object has no attribute 'strip'

This patch fixes the bug by skipping volumes without path.